on:
  workflow_dispatch: # autorise le dclenchement manuel du script
  
  push: # declenche le script au push sur master
    branches:
      - master

jobs:
  # first job
  hello: # job name
    runs-on: ubuntu-latest # runner -> os 
    steps:
      - name: step 1 
        run:  echo hello # a executer
      - name: step 2
        run:  ls -l
