on:
  workflow_dispatch: # autorise le dclenchement manuel du script
  
  push: # declenche le script au push sur master
    branches:
      - master

jobs:
  # first job
  hello: # job name
    runs-on: ubuntu-latest # runner -> os 
    steps:
      - name: import repo
        uses: actions/checkout@v5
      - name: listing
        run:  ls -l
      - name: .Net installation
        uses: actions/setup-dotnet@v5
        with: 
          dotnet-version: '8.x'
      - name: restore
        run:  dotnet restore
      - name: publish
        run:  dotnet build /publish
      - name: check publish folder
        run: ls -l /publish
